#app_homepage:
#    path:     /
#    defaults: { _controller: AppBundle:Main:index }

app_homepage:
    path:     /
    defaults: { _controller: FrameworkBundle:Redirect:urlRedirect, path: /blog, permanent: false }
